# Generated by Django 4.1.5 on 2023-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_title', models.CharField(max_length=100)),
                ('meetup_img', models.ImageField(upload_to='images/')),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
