# Generated by Django 4.1.5 on 2023-01-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('amount', models.CharField(default='1', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
