# Generated by Django 4.1.5 on 2023-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
